name: CI

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

  notify-telegram:
    runs-on: ubuntu-latest
    # Запускается всегда, независимо от успеха/фейла build
    if: always()
    steps:
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@v0.1.7
      with:
        to: 220894408
        token: 8669941278:AAE0uDdyTtcZSb7z8ZWBgKmM8SjfUyltLA8 
        message: |
          🚀 **CI Pipeline завершён**
          
          **Репозиторий**: ${{ github.repository }}
          **Бранч**: ${{ github.ref_name }}
          **Коммит**: ${{ github.sha }}
          **Статус**: ${{ job.status }}
          **Автор**: ${{ github.actor }}
          
          🔗 [Посмотреть коммит](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
